imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: zh_CN

assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    node: '%node_path%'
    filters:
        cssrewrite: ~
        uglifyjs2:
            bin: '%uglifyjs2_path%'

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  snc_redis.session.handler
        # save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    globals:
        assets_base_url: "%assets_base_url%"
        socket_host: '%socket_host%'
    strict_variables: "%kernel.debug%"
    form_themes:
        - "bootstrap_3_layout.html.twig"

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   pdo_mysql
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
                # if using pdo_sqlite as your database driver:
                #   1. add the path in parameters.yml
                #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
                #   2. Uncomment database_path in parameters.yml.dist
                #   3. Uncomment next line:
                #     path:     "%database_path%"
            spider:
                driver:   pdo_mysql
                host:     '127.0.0.1'
                port:     '3306'
                dbname:   'sf-spider'
                user:     'root'
                password: ''
                charset:   UTF8
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: 'doctrine.orm.naming_strategy.underscore'
        auto_mapping: true
        mappings:
            YesknWebBundle: ~


# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    port:       465
    encryption: ssl
    spool:     { type: memory }

snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: "%redis-dsn%"
        session:
            type: predis
            alias: session
            dsn: "%redis-dsn%"
        cache:
            type: predis
            alias: cache
            dsn: "%redis-dsn%"
            options:
                profile: 2.2
                connection_timeout: 10
                read_write_timeout: 30
    session:
        client: session
    doctrine:
        metadata_cache:
            client: cache
            entity_manager: default
            document_manager: default
        result_cache:
            client: cache
            entity_manager: default
        query_cache:
            client: cache
            entity_manager: default
        second_level_cache:
            client: cache
            entity_manager: default