imports:
    - { resource: config.yml }

framework:
    assets:
        version_strategy: Yeskn\MainBundle\Services\VersionStrategyService
        base_urls:
            - "%assets_base_url%"

monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
        nested:
            type: rotating_file
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
            max_files: 30
        console:
            type: console
            process_psr_3_messages: false
