imports:
    - { resource: config.yml }

framework:
    router:
        resource: '%kernel.config_dir%/routing_dev.yml'
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type: fingers_crossed
            level: debug
            channels: ['!event']
            handler: nested
        nested:
            type: rotating_file
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
            max_files: 30
        console:
            type: console
            process_psr_3_messages: false
            channels: ['!event', '!doctrine', '!console']
        server_log:
            type: server_log
            process_psr_3_messages: false
            host: 127.0.0.1:9911
