imports:
    - { resource: config.yml }

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

framework:
    assets:
        version_strategy: Yeskn\MainBundle\Services\VersionStrategyService
        base_urls:
            - "%assets_base_url%"

monolog:
    handlers:
        main:
            type: fingers_crossed
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            action_level: critical
            channels: ['!event']
            handler:      grouped
        grouped:
            type:    group
            members: [streamed, deduplicated]
        streamed:
            type:  stream
            path:  '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
        deduplicated:
            type:    deduplication
            handler: swift
        swift:
            type:       swift_mailer
            from_email: '%mailer_user%'
            to_email:   '%mailer_user%'
            subject:    'An Error Occurred! %%message%%'
            level:      error
            formatter:  monolog.formatter.html
            content_type: text/html
        console:
            type: console
            process_psr_3_messages: false
