vmoex_user:
    resource: "@YesknUserBundle/Controller"
    type:     annotation
    prefix:   /

vmoex_admin:
    resource: "@YesknAdminBundle/Controller"
    type:     annotation
    prefix:   /

vmoex_front:
    resource: "@YesknWebBundle/Controller/"
    type:     annotation
    prefix:   /

logout:
    path: /logout
