yeskn_oauth:
    resource: "@YesknOAuthBundle/Controller/"
    host:     oauth.yeskn.com
    type:     annotation
    prefix:   /

yeskn_admin:
    resource: "@YesknAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

yeskn_wpcraft:
    resource: "@YesknMainBundle/Controller/"
    type:     annotation
    prefix:   /
