yeskn_user:
    resource: "@YesknUserBundle/Controller"
    type:     annotation
    prefix:   /

yeskn_common:
    resource: "@YesknCommonBundle/Resources/config/routing.xml"
    prefix:   /

yeskn_admin:
    resource: "@YesknAdminBundle/Controller"
    type:     annotation
    prefix:   /

yeskn_blog:
    resource: "@YesknBlogBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

logout:
    path: /logout
