# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        Yeskn\BlogBundle\Entity\User: bcrypt
        Symfony\Component\Security\Core\User\User: plaintext

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        my_db_provider:
            entity:
                class: YesknBlogBundle:User
        in_memory:
            memory: ~

    firewalls:
        secured_area:
            pattern: ^/
            anonymous: true
            logout:
                # The route name the user can go to in order to logout
                path: /logout
                # The name of the route to redirect to after logging out
                target: /
            form_login:
                login_path: yeskn_user_login
                check_path: yeskn_login_check
            remember_me:
                secret: '%secret%'
                name: _token
                always_remember_me: true
                lifetime: 604800 # 1 week in seconds
                path: /
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:    ^/
            anonymous: ~
            logout: ~
            # activate different ways to authenticate

            http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

#            form_login:
#                login_path: yeskn_user_login
#                check_path: yeskn_user_login
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

            provider: my_db_provider

#            guard:
#                authenticators:
#                    - app.token_authenticator

#            remember_me:
#                secret: '%secret%'
#                name: _token
#                always_remember_me: true
#                lifetime: 604800 # 1 week in seconds
#                path: /

    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/admin , roles: ROLE_ADMIN }
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN,ROLE_ALLOWED_TO_SWITCH]
