# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    twig.extension.global_value:
        class: Yeskn\CommonBundle\Twig\GlobalValue
        arguments:
            $em: "@doctrine.orm.entity_manager"
            $translator: "@translator"
        tags:
            - { name: twig.extension }
    twig.extension.twig_extensions_intl:
        class: \Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    Yeskn\BlogBundle\EventListener\RequestListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 50 }

    Yeskn\BlogBundle\EventListener\ControllerListener:
        arguments: ['@service_container']
        tags:
            - { name: kernel.event_listener, event: kernel.controller }

    Yeskn\BlogBundle\EventListener\ResponseListener:
        arguments: ~
        tags:
          - { name: kernel.event_listener, event: kernel.response }

    form.string2image.transformer:
        class: Yeskn\BlogBundle\Form\DataTransformer\StringToImageTransformer
        arguments: ['@service_container']

    Yeskn\BlogBundle\Form\TabType:
        arguments: ['@service_container', '@form.string2image.transformer']
        tags: [form.type]

