services:
#    yeskn_blog.example:
#        class: Yeskn\WebBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

    socket.push:
        class: Yeskn\WebBundle\Services\SocketPushService
        arguments: ["@service_container"]
