services:

  _defaults:
      autowire: true      # Automatically injects dependencies in your services.
      autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
      public: false       # Allows optimizing the container by removing unused services; this also means
      # fetching services directly from the container via $container->get() won't work.
      # The best practice is to be explicit about your dependencies anyway.


  Yeskn\MainBundle\:
      resource: '../../../MainBundle/*'
      # you can exclude directories or files
      # but if a service is unused, it's removed anyway
      exclude: '../../../MainBundle/{Entity,Repository,Tests}'

    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
  Yeskn\MainBundle\Controller\:
      resource: '../../../MainBundle/Controller'
      public: true
      tags: ['controller.service_arguments']

  Yeskn\MainBundle\Form\Logic\ManageBasicLogic:
      arguments:
        - "@doctrine.orm.entity_manager"

  Yeskn\MainBundle\Form\ManageBasicType:
      arguments:
        - "%kernel.project_dir%"
      tags: [form.type]

  Yeskn\MainBundle\Form\TabType:
      arguments:
        - "%kernel.project_dir%"
      tags: [form.type]

  Yeskn\MainBundle\Form\UserMessageType:
      arguments:
        - "@doctrine.orm.entity_manager"
      tags: [form.type]


    # add more services, or override services that need manual wiring
    # AppBundle\Service\ExampleService:
    #     arguments:
    #         $someArgument: 'some_value'
  socket.push:
    class: Yeskn\MainBundle\Services\SocketPushService
    arguments:
      - "@service_container"
      - Yeskn\MainBundle\Twig\GlobalValue

  Yeskn\MainBundle\Twig\GlobalValue:
      arguments:
        $em: "@doctrine.orm.entity_manager"
        $translator: "@translator"
        $router: "@router"
        $tokenStorage: "@security.token_storage"
        $socketHost: "%socket_host%"
      tags:
      - { name: twig.extension }

  Yeskn\MainBundle\EventListener\AjaxAuthenticationListener:
    tags:
    - { name: kernel.event_listener, event: kernel.exception, method: onCoreException, priority: 1000 }