services:
#    yeskn_wpcraft.example:
#        class: Yeskn\WpcraftBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    # makes classes in src/AppBundle available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
  Yeskn\MainBundle\:
      resource: '../../../MainBundle/*'
      # you can exclude directories or files
      # but if a service is unused, it's removed anyway
      exclude: '../../../MainBundle/{Entity,Repository,Tests}'

    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
  Yeskn\MainBundle\Controller\:
      resource: '../../../MainBundle/Controller'
      public: true
      tags: ['controller.service_arguments']

    # add more services, or override services that need manual wiring
    # AppBundle\Service\ExampleService:
    #     arguments:
    #         $someArgument: 'some_value'